version: '3.7'


services:

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  bot:
    container_name: bot
    build: 
      context: .
    image: dchnkoo/tg-bot
    env_file:
      - .env