"""empty message

Revision ID: f88fbdb6b5b5
Revises: 
Create Date: 2024-03-02 10:38:59.105348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88fbdb6b5b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoryexesizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('recomendationstype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('treningtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('mediaexesizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media', sa.ARRAY(sa.String(), as_tuple=True, dimensions=2), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('buttons', sa.ARRAY(sa.String(), dimensions=3), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['categoryexesizes.type'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media', sa.ARRAY(sa.String(), as_tuple=True, dimensions=2), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('buttons', sa.ARRAY(sa.String(), dimensions=3), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['recomendationstype.type'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treningviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media', sa.ARRAY(sa.String(), as_tuple=True, dimensions=2), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('buttons', sa.ARRAY(sa.String(), dimensions=3), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['treningtypes.type'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treningviews')
    op.drop_table('recomendations')
    op.drop_table('mediaexesizes')
    op.drop_table('treningtypes')
    op.drop_table('recomendationstype')
    op.drop_table('categoryexesizes')
    # ### end Alembic commands ###
